version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./backend/src:/app/src

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
