version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${RAILWAY_PUBLIC_DOMAIN}/api
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL}
      - PORT=3000

# Railway will provide Redis as a separate service
# so we don't need to include it in our docker-compose file