version: '3'

services:
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    ports:
      - "8080:80"
    depends_on:
      - backend-test

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
