[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = ""
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments]
  production.services.backend.envs = { 
    NODE_ENV = "production", 
    REDIS_URL = "redis://default:AVOLAAIjcDFmNzVjNDVjZGM3MGY0NDczODEyMTA0NTAyOGNkMTc5OXAxMA@smiling-shrimp-21387.upstash.io:6379" 
  }
  production.services.frontend.envs = { 
    NODE_ENV = "production", 
    VITE_API_URL = "https://audit.mardenseo.com/api" 
  }