services:
  api:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      # Add other environment variables from .env file
    volumes:
      - ./src:/app/src
