[build]
dockerfilePath = "Dockerfile.test"
builder = "DOCKERFILE"

[deploy]
numReplicas = 1
startCommand = "node app.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
