name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Echo environment variables
        run: |
          echo "Checking railway token availability..."
          if [ -n "${{ secrets.RAILWAY_TOKEN }}" ]; then 
            echo "RAILWAY_TOKEN is set."
          else
            echo "RAILWAY_TOKEN is NOT set. Will need to be configured in GitHub repository secrets."
          fi

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway directly
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
